name = "EmeraldUtilities"
uuid = "bf152e34-6238-4522-95c8-8e628351fb48"
version = "0.1.0"
authors = ["Yujie Wang <jesiner@gmail.com>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[compat]
Dates = "1.11.0"
Distributed = "1.11.0"
