name = "EmeraldUtilities"
uuid = "bf152e34-6238-4522-95c8-8e628351fb48"
version = "1.0.0"
authors = ["Yujie Wang <jesiner@gmail.com>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
Dates = "1.11.0"
Distributed = "1.11.0"
DocStringExtensions = "0.9.5"
OrderedCollections = "1.8.1"
Statistics = "1.11.1"
StatsBase = "0.34.8"
TOML = "1.0.3"
Test = "1.11.0"
YAML = "0.4.16"
julia = "1.12"
