name = "EmeraldUtilities"
uuid = "bf152e34-6238-4522-95c8-8e628351fb48"
version = "0.1.0"
authors = ["Yujie Wang <jesiner@gmail.com>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
Dates = "1.11.0"
Distributed = "1.11.0"
OrderedCollections = "1.8.1"
TOML = "1.0.3"
Test = "1.11.0"
YAML = "0.4.16"
julia = "1.12"
