name = "PkgUtility"
uuid = "0d262f2c-28e9-492c-8e19-d7a5c4f11611"
version = "0.3.1"
authors = ["Yujie Wang <jesiner@gmail.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
Dates = "1.11.0"
Distributed = "1.11.0"
DocStringExtensions = "0.9.5"
GLM = "1.9.0"
OrderedCollections = "1.8.1"
Pkg = "1.12.0"
Statistics = "1.11.1"
StatsBase = "0.34.8"
TOML = "1.0.3"
Test = "1.11.0"
YAML = "0.4.16"
julia = "1.12"
